name: DDoS Bot Runner

on:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install python-telegram-bot scapy
          sudo apt-get update
          sudo apt-get install -y scapy
      - name: Run bot
        env:
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
        run: |
          sudo python ddos_bot.py
